version: '3.8'
services:
  auth:
    build: .
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=8082
      - JWT_SECRET="nbu8dTVEoJ/1pnIaOj+JM+Jrui/jLvtIKmXgGScb1ndzEfBb4GbqIz45gcMdRmb4ptfBNA1+/sCtttvpZPL8Vg"
      - JWT_EXPIRATION=3600 # 1 hora
      - GOOGLE_CLIENT_ID="97072811302-e0foheebjj6kto3k8efabljk2t453vbe.apps.googleusercontent.com"
      - GOOGLE_CLIENT_SECRET="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"
      - GOOGLE_REDIRECT_URL=http://localhost:3001/auth/callback
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=authuser
      - DB_PASSWORD=authpass
      - DB_NAME=authdb
      - DB_SSL_MODE=disable
      - FrontendURL=http://localhost:3001

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
